version: '3'
services:
  consul: 
    image: consul
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8500:8500
      - 8600:8600

  scout: 
    image: devgenie/scout:hashi
    hostname: scout.internal
    depends_on:
      - consul
    environment:
      - SERVICE_PORTS=8091
    ports:
      - 8091:8091
  scout2: 
    image: devgenie/scout:hashi
    hostname: scout2.internal
    depends_on:
      - consul
    environment:
      - SERVICE_PORTS=8091
    ports:
      - 8092:8091
  scout3: 
    image: devgenie/scout:hashi
    hostname: scout3.internal
    depends_on:
      - consul
    environment:
      - SERVICE_PORTS=8091
    ports:
      - 8093:8091